let article = prompt("Enter an Article: ")
let noun = prompt("Enter a Noun: ")
let adj = prompt("Enter an Adjective: ")
let verb = prompt("Enter a Verb: ")
let article2 = prompt("Enter an Article: ")
let adj2 = prompt("Enter another Adjective: ")
let noun2 = prompt("Enter another Noun: ")
console.log(article+ " "+ adj + " " + noun + " " + verb + " " + article2 + " " + adj2 + " " + noun2)
