var article = prompt("Enter an Article: ")
var noun = prompt("Enter a Noun: ")
var adj = prompt("Enter an Adjective: ")
var verb = prompt("Enter a Verb: ")
var article2 = prompt("Enter an Article: ")
var adj2 = prompt("Enter another Adjective: ")
var noun2 = prompt("Enter another Noun: ")
console.log(article+ " "+ adj + " " + noun + " " + verb + " " + article2 + " " + adj2 + " " + noun2)
